# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogbrief',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creatime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creater', models.CharField(max_length=50, verbose_name='创建人')),
                ('keywords', models.CharField(max_length=255, verbose_name='关键标签')),
                ('content', models.TextField(verbose_name='正文')),
            ],
            options={
                'verbose_name': '博客基础保存项',
                'verbose_name_plural': '博客基础保存项',
                'db_table': 'boke_blogbrief',
                'ordering': ['-updatetime'],
            },
        ),
    ]
