# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbrief',
            name='title',
            field=models.CharField(default='test', max_length=255, verbose_name='题目'),
            preserve_default=False,
        ),
    ]
