# Generated by Django 2.0.5 on 2018-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '2.图片',
                'verbose_name_plural': '2.图片',
                'db_table': 'blog_img',
            },
        ),
    ]
