# Generated by Django 2.0.5 on 2018-05-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogbrief',
            old_name='content',
            new_name='RichTextUploadingField',
        ),
    ]
