# Generated by Django 2.0.5 on 2018-05-19 13:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0002_auto_20180519_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbrief',
            name='RichTextUploadingField',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
    ]
