# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0002_blogbrief_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbrief',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
