# Generated by Django 2.0.5 on 2018-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0003_auto_20180519_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogbrief',
            old_name='RichTextUploadingField',
            new_name='content',
        ),
    ]
