# Generated by Django 2.0.5 on 2018-05-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0005_auto_20180520_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogbrief',
            old_name='creater',
            new_name='author',
        ),
    ]
